spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learnspacedb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      file-size-threshold: 0MB
  threads:
    virtual:
      enabled: true
course:
  page_size: 20
review:
  page_size: 2
